import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../cloudflare-worker.js';
const origin='https://studio.test';
function request(body,headers={}){return new Request(origin+'/api/subscribe',{method:'POST',headers:{Origin:origin,...headers},body:JSON.stringify(body)})}
const valid={email:' Test@Example.com ',consent:true,website:''};
function store(){const data=new Map();return {data,async get(k){return data.has(k)?JSON.parse(data.get(k)):null},async put(k,v){data.set(k,v)}}}
test('rejects invalid consent, email, honeypot, and foreign origin',async()=>{for(const body of [{...valid,consent:false},{...valid,email:'bad'},{...valid,website:'spam'}])assert.equal((await worker.fetch(request(body),{})).status,400);assert.equal((await worker.fetch(request(valid,{Origin:'https://other.test'}),{})).status,403)});
test('rejects oversized bodies even without a Content-Length header',async()=>{assert.equal((await worker.fetch(request({...valid,extra:'x'.repeat(5000)}),{})).status,413)});
test('reports storage failure instead of false success',async()=>{assert.equal((await worker.fetch(request(valid),{})).status,503);assert.equal((await worker.fetch(request(valid),{SUBSCRIBERS:{get(){throw Error()}}})).status,503)});
test('saves normalized subscriber, records activation state, avoids duplicate accepted notifications',async()=>{const original=globalThis.fetch;const kv=store();let calls=0;try{globalThis.fetch=async()=>{calls++;return Response.json({success:'false',message:'This form needs Activation.'})};assert.equal((await worker.fetch(request(valid),{SUBSCRIBERS:kv})).status,200);let record=JSON.parse([...kv.data.values()][0]);assert.equal(record.email,'test@example.com');assert.equal(record.notification,'activation_required');globalThis.fetch=async()=>{calls++;return Response.json({success:'true'})};await worker.fetch(request(valid),{SUBSCRIBERS:kv});await worker.fetch(request(valid),{SUBSCRIBERS:kv});assert.equal(calls,2);assert.equal(JSON.parse([...kv.data.values()][0]).notification,'accepted')}finally{globalThis.fetch=original}});
test('notification failure preserves the successfully saved signup',async()=>{const original=globalThis.fetch;const kv=store();try{globalThis.fetch=async()=>{throw Error('offline')};assert.equal((await worker.fetch(request(valid),{SUBSCRIBERS:kv})).status,200);assert.equal(JSON.parse([...kv.data.values()][0]).notification,'failed')}finally{globalThis.fetch=original}});
test('contact inquiries retain message and allow newsletter opt-out',async()=>{const original=globalThis.fetch;const kv=store();let sent;try{globalThis.fetch=async(_,init)=>{sent=JSON.parse(init.body);return Response.json({success:true})};assert.equal((await worker.fetch(request({...valid,kind:'contact',consent:false,message:'Help with my shop'}),{SUBSCRIBERS:kv})).status,200);const record=JSON.parse([...kv.data.values()][0]);assert.equal(record.consent,false);assert.equal(record.message,'Help with my shop');assert.match(sent.message,/Newsletter opt-in: No/);assert.match(sent.message,/Help with my shop/)}finally{globalThis.fetch=original}});
